### ISSUE TITLE
Subscribe depth@100ms, return empty content

### ISSUE THREAD

**Issue by 10ucapital** [Bohr1005/xcrypto#5]
Changed subscribed stream at context.py, trade.rs and chat.rs

In demo.py: 
sub = session.subscribe("dogefdusd", "depth@100ms")

return:
Datetime: 2024-06-24 01:19:22.493000+08:00, Symbol: dogefdusd
Best Bid Price: 0.0, Best Bid Quantity: 0.0
Best Ask Price: 0.12294, Best Ask Quantity: 46397.0
Datetime: 2024-06-24 01:19:22.793000+08:00, Symbol: dogefdusd
Best Bid Price: 0.0, Best Bid Quantity: 0.0
Best Ask Price: 0.12293, Best Ask Quantity: 51631.0
Datetime: 2024-06-24 01:19:22.893000+08:00, Symbol: dogefdusd
Best Bid Price: 0.12287, Best Bid Quantity: 35245.0
Best Ask Price: 0.12292, Best Ask Quantity: 21617.0
Datetime: 2024-06-24 01:19:22.993000+08:00, Symbol: dogefdusd
Best Bid Price: 0.0, Best Bid Quantity: 0.0
Best Ask Price: 0.12292, Best Ask Quantity: 23650.0
Datetime: 2024-06-24 01:19:23.093000+08:00, Symbol: dogefdusd
Best Bid Price: 0.0, Best Bid Quantity: 0.0
Best Ask Price: 0.0, Best Ask Quantity: 0.0

**Comment by Bohr1005** [comment]
depth@100ms is not supported currently, but I will implement it

**Comment by Bohr1005** [comment]
bbo,depth:100ms is avaliable now, please pull the lastest code and rebuild xcrypto, pyalgo. market stream details can be found in README.md. best wishes for your trading
