### ISSUE TITLE
浮点数精度问题与传参

### ISSUE THREAD

**Issue by 10ucapital** [Bohr1005/xcrypto#6]
实践中出现了浮点数转换精度问题，应该是出现在pyalgo/subscription.rs中的round_price和floor_to_lot_size函数中。简单改了一下，pyo3传decimal好像并不原生支持。

Order {
    time: 1719646291875,
    symbol: "ethfdusd",
    side: BUY,
    state: REJECTED,
    order_type: LIMIT,
    tif: GTC,
    quantity: 0.0058000000000000005,
    price: 3397.52,
    order_id: -1,
    internal_id: 51,
    trade_time: 0,
    trade_price: 0.0,
    trade_quantity: 0.0,
    acc: 0.0,
    making: false,
}

**Comment by 10ucapital** [comment]
好像我在传入rust那边改掉就好了。

**Comment by Bohr1005** [comment]
可以提个pr吗，我合并一下你的代码

**Comment by Bohr1005** [comment]
可以提个pr吗，我合并一下你的代码

**Comment by Bohr1005** [comment]
已经提交最新的代码到main分支，目测应该是解决了精度问题

**Comment by 10ucapital** [comment]
大佬动作还是快 thx

**Comment by 10ucapital** [comment]
0|spot     | Price: 63903.05, Quantity: 0.0005000000000000001
0|spot     | Price: 63895.3, Quantity: 0.0005000000000000001
0|spot     | Price: 63903.05, Quantity: 0.0005000000000000001
0|spot     | Price: 63892.76, Quantity: 0.0005000000000000001

quantity似乎还会有这个问题。我简单粗暴地在binance/spot/src/trade.rs改掉了：
108行add_order函数内：
let price = (price*100.0).round()/100.0;
let quantity = (quantity*10000000.0).round()/10000000.0;

**Comment by Bohr1005** [comment]
这是现货btc吗，你的下单数量是0.0005是吗

**Comment by 10ucapital** [comment]
是的。btcfdusd

quant_bohr ***@***.***> 于 2024年7月19日周五 11:11写道：
